"""add safety plans

Revision ID: 8c77a5408feb
Revises: 6c4a46ecbad7
Create Date: 2026-08-12 02:50:08.962713

"""
from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. app.crypto.EncryptedText) are rendered fully
# qualified by autogenerate, so this import must always be present.
import app.crypto


# revision identifiers, used by Alembic.
revision = '8c77a5408feb'
down_revision = '6c4a46ecbad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('warning_signs', app.crypto.EncryptedText(), nullable=True),
    sa.Column('coping_strategies', app.crypto.EncryptedText(), nullable=True),
    sa.Column('distractions', app.crypto.EncryptedText(), nullable=True),
    sa.Column('support_people', app.crypto.EncryptedText(), nullable=True),
    sa.Column('professionals', app.crypto.EncryptedText(), nullable=True),
    sa.Column('environment', app.crypto.EncryptedText(), nullable=True),
    sa.Column('reasons_for_living', app.crypto.EncryptedText(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_plans_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safety_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_plans_user_id'))

    op.drop_table('safety_plans')
    # ### end Alembic commands ###
